config/routes.rb
Rails.application.routes.draw do
	root "user#index"
	get 'user/regest' => "user#regest",:as => "regest"
	get "user/login" => "user#login" ,:as => "login"
	post "user/create" => "user#create",:as => "create"
	post "user/login_session" => "user#login_session",:as => "login_session"
	get "user/logout" => "user#logout",:as => "logout"
	get "user/delete/:id" => "user#delete",:as => "delete"
	get "user/change/:id" => "user#change",:as => "change"
	post "user/update/:id" => "user#update",:as => "update"
	get "user/user_center" => "user#user_center",:as => "user_center"
	

	get 'note/index' => "note#index",:as => "note_index"
	get 'note/new' => "note#new",:as =>"note_new"
	post "note/create" => "note#create",:as => "note_create"
	get "note/delete/:id" => "note#delete",:as => "note_delete"
	get 'note/change/:id' => "note#change",:as => "note_change"
	post "note/update/:id" => "note#update",:as => "note_update"
	get "note/show/:id" => "note#show",:as => "note_show"
	post "note/:note_id/comment/create" => "comment#create",:as => "comment_create"
	get "note/:note_id/comment/delete/:comment_id" => "comment#delete",:as =>"comment_delete"

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :note
	belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	has_many :comments,:dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
	has_many :notes,:dependent => :destroy
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery :only => :login

	private
		def current_user
			@current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
		end

	helper_method :current_user
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def create
		c = params[:content]
		note_id = params[:note_id]
		@comment = Comment.create(:content => c,:user_id => session[:user_id],:note_id => note_id)
		respond_to do |format|
			format.js
		end
	end

	def delete
		Comment.find(params[:comment_id]).destroy
		redirect_to note_show_path(params[:note_id])
	end
end

app/controllers/note_controller.rb
class NoteController < ApplicationController
  before_action :need_login,:only => :create

  def need_login
    if !current_user
      redirect_to :login
    end
  end

  
  def index
  	@note = Note.all.reverse
  end

  def new
  end

  def change
  	@note = Note.find_by_id(params[:id])
  end

  def create
  	title = params[:title]
  	content = params[:content]
  	Note.create(:title => title,:content => content,:user_id => session[:user_id])
  	redirect_to :note_index
  end

  def update
  	note = Note.find_by_id(params[:id])
  	title = params[:title]
  	content = params[:content]
  	note.title = title
  	note.content = content
  	note.save
  	redirect_to :note_index
  end

  def delete
  	Note.find_by_id(params[:id]).destroy
  	redirect_to :note_index
  end

  def show
    @note = Note.find(params[:id])
    @comment = @note.comments
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :need_login,:only => :user_center

	def need_login
		if !current_user
			redirect_to :login
		end
	end


	def index
		@user = User.all
	end

	def regest
		@user = User.new
	end

	def login
	end
	
	def create
		qwe = params[:username]
		password = params[:password]
		User.create(:username => qwe,:password => password)
		redirect_to :login
	end


	# def user_params
	# 	params.require(:user).permit(:username,:password)
	# end

	def login_session
		username = params[:username]
		password = params[:password]
		@user = User.find_by_username(username)
		if @user && @user.password == password
			session[:user_id] = @user.id
			redirect_to :root
		else
			redirect_to :login
		end
	end
	def logout
		session[:user_id] = nil
		redirect_to :root
	end

	def delete
		user_id = params[:id]
		User.find_by_id(user_id).destroy
		redirect_to :root
	end

	def change
		@user = User.find_by_id(params[:id])
	end

	def update
		user = User.find_by_id(params[:id])
		user.username = params[:username]
		user.password = params[:password]
		user.save
		redirect_to :root
	end

	def user_center
		@note = current_user.notes
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/_comment_h.html.erb
<div class="media">
	<div class="media-body">
	    <h4 class="media-heading"><%= c.user.username %></h4>
	    <%= c.content %>
	    <% if current_user.id == c.user.id %>
	    	<a href="<%= comment_delete_path(c.note.id,c.id) %>">删除</a>
	    <% end %>
	</div>
</div>

app/views/comment/create.js.erb
$(".comment").append('<%= j(render :partial => "comment/comment_h",:locals => {:c => @comment}) %>')
$("textarea").val("")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="/">Blog</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "帖子首页",note_index_path %></li>
            <% if !current_user %>
            <!--   <li><a href="/user/login">登录</a></li> -->

              <li><%= link_to "登录",login_path %></li>
              <li><a href="/user/regest">注册</a></li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">欢迎&nbsp;&nbsp;<%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="<%= user_center_path %>">个人中心</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="<%= note_new_path %>">新建帖子</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="/user/logout">退出登录</a></li>
                </ul>
              </li>
            <% end %>
            </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/note/change.html.erb
<form action="<%= note_update_path %>" method="post">
	<div class="form-group">
	 	<label for="title">标题</label>
	    <input type="text" class="form-control" id="title" name="title" value="<%= @note.title %>">
	</div>
	<div class="form-group">
	 	<label for="content">内容</label>
	    <textarea class="form-control" rows="3" id="content" name="content"><%= @note.content %></textarea>
	</div>
	<button type="submit" class="btn btn-default">修改</button>
</form>

app/views/note/index.html.erb
<table class="table table-bordered text-center">
	<thead>
		<tr>
			<th>帖子编号</th>
			<th>标题</th>
			<th>内容</th>
			<th>作者</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @note.each do |i| %>
			<tr>
				<td><%= i.id %></td>
				<td>
					<a href="<%= note_show_path i.id %>"><%= i.title %></a>
				</td>
				<td><%= i.content %></td>
				<td><%= i.user.username %></td>
				<td>
					<a href="<%= note_delete_path(i.id) %>" class="btn btn-danger" method="delete">删除</a>
					<a href="<%= note_change_path(i.id) %>" class="btn btn-primary">修改</a>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/note/new.html.erb
<form action="<%= note_create_path %>" method="post">
	<div class="form-group">
	 	<label for="title">标题</label>
	    <input type="text" class="form-control" id="title" name="title">
	</div>
	<div class="form-group">
	 	<label for="content">内容</label>
	    <textarea class="form-control" rows="3" id="content" name="content"></textarea>
	</div>
	<button type="submit" class="btn btn-default">发布</button>
</form>

app/views/note/show.html.erb
<div class="jumbotron">
	<h1><%= @note.title %></h1>
	<p><%= @note.content %></p>
	<p><span>作者：<%= @note.user.username %></span></p>
</div>
<hr>

<div class="comment">
	<% @comment.each do |c| %>
		<%= render :partial => "comment/comment_h",:locals => {:c => c} %>
	<% end %>
</div>




<hr>
<form action="<%= comment_create_path(@note.id) %>" method="post" data-remote="true">
	<div class="form-group">
	 	<label for="content">评论内容</label>
	    <textarea class="form-control" rows="3" id="content" name="content"></textarea>
	</div>
	<button type="submit" class="btn btn-default">发布</button>
</form>

app/views/user/_form.html.erb
<form action="<%= url %>" method="post" data-remote="true">
	<div class="form-group">
	    <label for="username">用户名</label>
	    <input type="text" class="form-control" id="username" placeholder="请于此输入用户名" name="username" <% if user != nil %> value="<%= user.username %>" <% end %>>
  	</div>
  	<div class="form-group">
	    <label for="password">密码</label>
	    <input type="password" class="form-control" id="password" placeholder="请于此输入密码" name="password" <% if user != nil %> value="<%= user.password %>"
	    <% end %>
	    >
  	</div>
  	<% if lOrR == 0 %>
	  	<button type="submit" class="btn btn-info">登录</button>
	<% elsif lOrR == 2 %>
		<button type="submit" class="btn btn-primary">修改</button>
	<% else %>
		<button type="submit" class="btn btn-danger">注册</button>
	<% end %>
</form>

app/views/user/change.html.erb
<%= render :partial => "form",:locals => {:url => update_path,:lOrR => 2,:user => @user} %>

app/views/user/index.html.erb
<table class="table table-bordered text-center">
	<thead>
		<tr>
			<th>用户编号</th>
			<th>用户姓名</th>
			<th>用户密码</th>
			<th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @user.each do |user| %>
			<tr>
				<td><%= user.id %></td>
				<td><%= user.username %></td>
				<td><%= user.password %></td>
				<td>
					<% if current_user %>
						<a href="<%= delete_path(user.id) %>" class="btn btn-danger">删除</a>
						<a href="<%= change_path(user.id) %>" class="btn btn-primary">修改</a>
					<% else %>
						<%= link_to "请登录",login_path %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/user/login.html.erb
<%=  render :partial => "form",:locals => {:url => login_session_path,:lOrR => 0,:user => nil} %>

app/views/user/regest.html.erb
<%= render :partial => "form",:locals => {:url => create_path,:lOrR => 1,:user => nil} %>

app/views/user/user_center.html.erb
<ul class="list-group">
	<% @note.each do |i| %>
		<li class="list-group-item"><%= i.title %></li>
	<% end %>
</ul>